"""
Script para cargar actividades de ejemplo en la base de datos.
Se corre una sola vez (o cada que quieras reiniciar el catálogo) con:
    python seed_actividades.py
"""

from app import create_app
from extensions import db
from models import Actividad

actividades_ejemplo = [
    {"nombre": 'Sentadilla', "categoria": 'pesas', "grupo_muscular": 'Cuádriceps',
     "descripcion": 'Ejercicio compuesto para piernas y glúteos.', "imagen": 'sentadilla.jpg'},
    {"nombre": 'Prensa de piernas', "categoria": 'pesas', "grupo_muscular": 'Cuádriceps',
     "descripcion": 'Trabaja cuádriceps con apoyo de máquina.', "imagen": 'prensa.jpg'},
    {"nombre": 'Zancadas', "categoria": 'pesas', "grupo_muscular": 'Cuádriceps',
     "descripcion": 'Ejercicio unilateral para piernas y glúteos.', "imagen": 'zancadas.jpg'},
    {"nombre": 'Sentadilla búlgara', "categoria": 'pesas', "grupo_muscular": 'Cuádriceps',
     "descripcion": 'Variante unilateral con pie trasero elevado.', "imagen": 'sentadilla_bulgara.jpg'},
    {"nombre": 'Sentadilla frontal', "categoria": 'pesas', "grupo_muscular": 'Cuádriceps',
     "descripcion": 'Sentadilla con barra al frente, más énfasis en cuádriceps.', "imagen": 'sentadilla_frontal.jpg'},
    {"nombre": 'Hack squat', "categoria": 'pesas', "grupo_muscular": 'Cuádriceps',
     "descripcion": 'Sentadilla guiada en máquina.', "imagen": 'hack_squat.jpg'},
    {"nombre": 'Extensión de piernas', "categoria": 'pesas', "grupo_muscular": 'Cuádriceps',
     "descripcion": 'Aislamiento de cuádriceps en máquina.', "imagen": 'extension_piernas.jpg'},
    {"nombre": 'Sentadilla goblet', "categoria": 'pesas', "grupo_muscular": 'Cuádriceps',
     "descripcion": 'Sentadilla sosteniendo una mancuerna o kettlebell al pecho.', "imagen": 'sentadilla_goblet.jpg'},
    {"nombre": 'Zancada caminando', "categoria": 'pesas', "grupo_muscular": 'Cuádriceps',
     "descripcion": 'Zancadas en desplazamiento continuo.', "imagen": 'zancada_caminando.jpg'},
    {"nombre": 'Peso muerto rumano', "categoria": 'pesas', "grupo_muscular": 'Isquiotibiales',
     "descripcion": 'Enfatiza isquiotibiales y glúteos con piernas semi-rígidas.', "imagen": 'peso_muerto_rumano.jpg'},
    {"nombre": 'Curl femoral', "categoria": 'pesas', "grupo_muscular": 'Isquiotibiales',
     "descripcion": 'Aislamiento de isquiotibiales en máquina.', "imagen": 'curl_femoral.jpg'},
    {"nombre": 'Buenos días', "categoria": 'pesas', "grupo_muscular": 'Isquiotibiales',
     "descripcion": 'Flexión de cadera con barra en espalda alta.', "imagen": 'buenos_dias.jpg'},
    {"nombre": 'Peso muerto piernas rígidas', "categoria": 'pesas', "grupo_muscular": 'Isquiotibiales',
     "descripcion": 'Variante de peso muerto con rango amplio.', "imagen": 'peso_muerto_rigido.jpg'},
    {"nombre": 'Curl nórdico', "categoria": 'pesas', "grupo_muscular": 'Isquiotibiales',
     "descripcion": 'Ejercicio excéntrico con peso corporal.', "imagen": 'curl_nordico.jpg'},
    {"nombre": 'Hip thrust', "categoria": 'pesas', "grupo_muscular": 'Glúteos',
     "descripcion": 'Ejercicio de aislamiento para glúteos.', "imagen": 'hip_thrust.jpg'},
    {"nombre": 'Patada de glúteo', "categoria": 'pesas', "grupo_muscular": 'Glúteos',
     "descripcion": 'Extensión de cadera en polea o máquina.', "imagen": 'patada_gluteo.jpg'},
    {"nombre": 'Abducción de cadera', "categoria": 'pesas', "grupo_muscular": 'Glúteos',
     "descripcion": 'Aislamiento de glúteo medio en máquina.', "imagen": 'abduccion_cadera.jpg'},
    {"nombre": 'Puente de glúteo', "categoria": 'pesas', "grupo_muscular": 'Glúteos',
     "descripcion": 'Variante en piso, buena para principiantes.', "imagen": 'puente_gluteo.jpg'},
    {"nombre": 'Step up', "categoria": 'pesas', "grupo_muscular": 'Glúteos',
     "descripcion": 'Subida a plataforma con peso.', "imagen": 'step_up.jpg'},
    {"nombre": 'Peso muerto sumo', "categoria": 'pesas', "grupo_muscular": 'Glúteos',
     "descripcion": 'Variante de peso muerto con postura abierta.', "imagen": 'peso_muerto_sumo.jpg'},
    {"nombre": 'Elevación de talones de pie', "categoria": 'pesas', "grupo_muscular": 'Pantorrillas',
     "descripcion": 'Ejercicio base para gemelos.', "imagen": 'elevacion_talones_pie.jpg'},
    {"nombre": 'Elevación de talones sentado', "categoria": 'pesas', "grupo_muscular": 'Pantorrillas',
     "descripcion": 'Enfatiza el sóleo.', "imagen": 'elevacion_talones_sentado.jpg'},
    {"nombre": 'Elevación de talones en prensa', "categoria": 'pesas', "grupo_muscular": 'Pantorrillas',
     "descripcion": 'Variante en máquina de prensa.', "imagen": 'elevacion_talones_prensa.jpg'},
    {"nombre": 'Press de banca', "categoria": 'pesas', "grupo_muscular": 'Pecho',
     "descripcion": 'Ejercicio base para pecho, hombros y tríceps.', "imagen": 'press_banca.jpg'},
    {"nombre": 'Press inclinado', "categoria": 'pesas', "grupo_muscular": 'Pecho',
     "descripcion": 'Enfatiza la parte superior del pecho.', "imagen": 'press_inclinado.jpg'},
    {"nombre": 'Press declinado', "categoria": 'pesas', "grupo_muscular": 'Pecho',
     "descripcion": 'Enfatiza la parte inferior del pecho.', "imagen": 'press_declinado.jpg'},
    {"nombre": 'Aperturas con mancuerna', "categoria": 'pesas', "grupo_muscular": 'Pecho',
     "descripcion": 'Aislamiento de pecho con rango amplio.', "imagen": 'aperturas.jpg'},
    {"nombre": 'Press con mancuernas', "categoria": 'pesas', "grupo_muscular": 'Pecho',
     "descripcion": 'Variante con mayor rango de movimiento.', "imagen": 'press_mancuernas.jpg'},
    {"nombre": 'Cruces en polea', "categoria": 'pesas', "grupo_muscular": 'Pecho',
     "descripcion": 'Aislamiento de pecho en polea alta o baja.', "imagen": 'cruces_polea.jpg'},
    {"nombre": 'Flexiones de pecho', "categoria": 'pesas', "grupo_muscular": 'Pecho',
     "descripcion": 'Ejercicio con peso corporal.', "imagen": 'flexiones.jpg'},
    {"nombre": 'Peso muerto', "categoria": 'pesas', "grupo_muscular": 'Espalda',
     "descripcion": 'Ejercicio compuesto para espalda baja y piernas.', "imagen": 'peso_muerto.jpg'},
    {"nombre": 'Dominadas', "categoria": 'pesas', "grupo_muscular": 'Espalda',
     "descripcion": 'Ejercicio con peso corporal para espalda y bíceps.', "imagen": 'dominadas.jpg'},
    {"nombre": 'Remo con barra', "categoria": 'pesas', "grupo_muscular": 'Espalda',
     "descripcion": 'Trabaja espalda media con barra libre.', "imagen": 'remo_barra.jpg'},
    {"nombre": 'Jalón al pecho', "categoria": 'pesas', "grupo_muscular": 'Espalda',
     "descripcion": 'Variante en máquina, buena para principiantes.', "imagen": 'jalon_pecho.jpg'},
    {"nombre": 'Remo con mancuerna', "categoria": 'pesas', "grupo_muscular": 'Espalda',
     "descripcion": 'Remo unilateral apoyado en banco.', "imagen": 'remo_mancuerna.jpg'},
    {"nombre": 'Remo en polea baja', "categoria": 'pesas', "grupo_muscular": 'Espalda',
     "descripcion": 'Remo sentado con cable.', "imagen": 'remo_polea.jpg'},
    {"nombre": 'Pull-over', "categoria": 'pesas', "grupo_muscular": 'Espalda',
     "descripcion": 'Trabaja dorsales y serrato con mancuerna.', "imagen": 'pull_over.jpg'},
    {"nombre": 'Press militar', "categoria": 'pesas', "grupo_muscular": 'Hombros',
     "descripcion": 'Ejercicio para desarrollar hombros.', "imagen": 'press_militar.jpg'},
    {"nombre": 'Elevaciones laterales', "categoria": 'pesas', "grupo_muscular": 'Hombros',
     "descripcion": 'Aislamiento del deltoides lateral.', "imagen": 'elevaciones_laterales.jpg'},
    {"nombre": 'Elevaciones frontales', "categoria": 'pesas', "grupo_muscular": 'Hombros',
     "descripcion": 'Aislamiento del deltoides frontal.', "imagen": 'elevaciones_frontales.jpg'},
    {"nombre": 'Pájaros (deltoide posterior)', "categoria": 'pesas', "grupo_muscular": 'Hombros',
     "descripcion": 'Aislamiento del deltoide posterior.', "imagen": 'pajaros.jpg'},
    {"nombre": 'Press Arnold', "categoria": 'pesas', "grupo_muscular": 'Hombros',
     "descripcion": 'Variante de press con rotación de muñeca.', "imagen": 'press_arnold.jpg'},
    {"nombre": 'Remo al mentón', "categoria": 'pesas', "grupo_muscular": 'Hombros',
     "descripcion": 'Trabaja hombros y trapecio.', "imagen": 'remo_menton.jpg'},
    {"nombre": 'Curl con barra', "categoria": 'pesas', "grupo_muscular": 'Bíceps',
     "descripcion": 'Ejercicio base para bíceps.', "imagen": 'curl_barra.jpg'},
    {"nombre": 'Curl con mancuerna', "categoria": 'pesas', "grupo_muscular": 'Bíceps',
     "descripcion": 'Variante unilateral o alterna.', "imagen": 'curl_mancuerna.jpg'},
    {"nombre": 'Curl martillo', "categoria": 'pesas', "grupo_muscular": 'Bíceps',
     "descripcion": 'Trabaja bíceps y antebrazo.', "imagen": 'curl_martillo.jpg'},
    {"nombre": 'Curl en banco Scott', "categoria": 'pesas', "grupo_muscular": 'Bíceps',
     "descripcion": 'Aislamiento con apoyo de banco.', "imagen": 'curl_scott.jpg'},
    {"nombre": 'Curl en polea', "categoria": 'pesas', "grupo_muscular": 'Bíceps',
     "descripcion": 'Variante con tensión constante.', "imagen": 'curl_polea.jpg'},
    {"nombre": 'Press francés', "categoria": 'pesas', "grupo_muscular": 'Tríceps',
     "descripcion": 'Aislamiento de tríceps con barra o mancuerna.', "imagen": 'press_frances.jpg'},
    {"nombre": 'Fondos en paralelas', "categoria": 'pesas', "grupo_muscular": 'Tríceps',
     "descripcion": 'Ejercicio con peso corporal para tríceps y pecho.', "imagen": 'fondos.jpg'},
    {"nombre": 'Extensión de tríceps en polea', "categoria": 'pesas', "grupo_muscular": 'Tríceps',
     "descripcion": 'Ejercicio en polea alta con cuerda o barra.', "imagen": 'extension_triceps_polea.jpg'},
    {"nombre": 'Patada de tríceps', "categoria": 'pesas', "grupo_muscular": 'Tríceps',
     "descripcion": 'Aislamiento con mancuerna, torso inclinado.', "imagen": 'patada_triceps.jpg'},
    {"nombre": 'Press cerrado en banca', "categoria": 'pesas', "grupo_muscular": 'Tríceps',
     "descripcion": 'Press de banca con agarre cerrado.', "imagen": 'press_cerrado.jpg'},
    {"nombre": 'Plancha', "categoria": 'pesas', "grupo_muscular": 'Abdomen',
     "descripcion": 'Ejercicio isométrico para el core.', "imagen": 'plancha.jpg'},
    {"nombre": 'Elevación de piernas', "categoria": 'pesas', "grupo_muscular": 'Abdomen',
     "descripcion": 'Trabaja abdomen bajo colgado o acostado.', "imagen": 'elevacion_piernas.jpg'},
    {"nombre": 'Crunch abdominal', "categoria": 'pesas', "grupo_muscular": 'Abdomen',
     "descripcion": 'Ejercicio clásico de abdomen superior.', "imagen": 'crunch.jpg'},
    {"nombre": 'Rueda abdominal', "categoria": 'pesas', "grupo_muscular": 'Abdomen',
     "descripcion": 'Ejercicio avanzado de core completo.', "imagen": 'rueda_abdominal.jpg'},
    {"nombre": 'Giro ruso', "categoria": 'pesas', "grupo_muscular": 'Abdomen',
     "descripcion": 'Trabaja oblicuos con rotación de torso.', "imagen": 'giro_ruso.jpg'},
    {"nombre": 'Plancha lateral', "categoria": 'pesas', "grupo_muscular": 'Abdomen',
     "descripcion": 'Isométrico enfocado en oblicuos.', "imagen": 'plancha_lateral.jpg'},
    {"nombre": 'Curl de muñeca', "categoria": 'pesas', "grupo_muscular": 'Antebrazo',
     "descripcion": 'Aislamiento de flexores del antebrazo.', "imagen": 'curl_muneca.jpg'},
    {"nombre": "Farmer's walk", "categoria": 'pesas', "grupo_muscular": 'Antebrazo',
     "descripcion": 'Caminata cargando peso en ambas manos.', "imagen": 'farmers_walk.jpg'},
    {"nombre": 'Encogimientos (shrugs)', "categoria": 'pesas', "grupo_muscular": 'Trapecio',
     "descripcion": 'Aislamiento de trapecio superior.', "imagen": 'shrugs.jpg'},
    {"nombre": 'Burpees', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Ejercicio funcional de cuerpo completo, alta intensidad.', "imagen": 'burpees.jpg'},
    {"nombre": 'Kettlebell swing', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Movimiento explosivo de cadera con pesa rusa.', "imagen": 'kettlebell.jpg'},
    {"nombre": 'Box jump', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Salto explosivo sobre una caja o plataforma.', "imagen": 'box_jump.jpg'},
    {"nombre": 'Wall ball', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Lanzamiento de balón medicinal a una pared.', "imagen": 'wall_ball.jpg'},
    {"nombre": 'Thrusters', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Sentadilla frontal combinada con press de hombro.', "imagen": 'thrusters.jpg'},
    {"nombre": 'Double unders', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Salto de cuerda con doble paso por vuelta.', "imagen": 'double_unders.jpg'},
    {"nombre": 'Muscle-up', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Movimiento avanzado que combina dominada y fondo.', "imagen": 'muscle_up.jpg'},
    {"nombre": 'Sled push', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Empuje de trineo con peso, fuerza y resistencia.', "imagen": 'sled_push.jpg'},
    {"nombre": 'Clean and jerk', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Levantamiento olímpico de barra del suelo sobre la cabeza.', "imagen": 'clean_jerk.jpg'},
    {"nombre": 'Snatch', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Levantamiento olímpico en un solo movimiento.', "imagen": 'snatch.jpg'},
    {"nombre": 'Toes to bar', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Elevación de piernas hasta la barra, colgado.', "imagen": 'toes_to_bar.jpg'},
    {"nombre": 'Battle ropes', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Ondulaciones de cuerda de alta intensidad.', "imagen": 'battle_ropes.jpg'},
    {"nombre": 'Rope climb', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Escalada de cuerda, fuerza de agarre y tren superior.', "imagen": 'rope_climb.jpg'},
    {"nombre": 'Devil press', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Combinación de burpee con press de mancuernas.', "imagen": 'devil_press.jpg'},
    {"nombre": 'Air squat', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Sentadilla con peso corporal a ritmo alto.', "imagen": 'air_squat.jpg'},
    {"nombre": 'Correr', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Actividad cardiovascular al aire libre o en caminadora.', "imagen": 'correr.jpg'},
    {"nombre": 'Natación', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Actividad de bajo impacto, trabaja todo el cuerpo.', "imagen": 'natacion.jpg'},
    {"nombre": 'Bicicleta', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Cardio de bajo impacto, ideal para resistencia.', "imagen": 'bicicleta.jpg'},
    {"nombre": 'Cuerda (saltar)', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Cardio de alta intensidad, mejora coordinación.', "imagen": 'cuerda.jpg'},
    {"nombre": 'Remo (máquina)', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Cardio de cuerpo completo con máquina de remo.', "imagen": 'remo_maquina.jpg'},
    {"nombre": 'Elíptica', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Cardio de bajo impacto para articulaciones.', "imagen": 'eliptica.jpg'},
    {"nombre": 'Caminadora inclinada', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Caminata con inclinación, buena para resistencia.', "imagen": 'caminadora.jpg'},
    {"nombre": 'Escaladora', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Simula subir escaleras, alta demanda cardiovascular.', "imagen": 'escaladora.jpg'},
    {"nombre": 'Caminata', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Cardio de bajo impacto, ideal para principiantes.', "imagen": 'caminata.jpg'},
    {"nombre": 'Spinning', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Ciclismo indoor de alta intensidad en grupo.', "imagen": 'spinning.jpg'},
    {"nombre": 'Zumba', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Cardio con baile, dinámico y de intensidad variable.', "imagen": 'zumba.jpg'},
    {"nombre": 'Boxeo (sombra)', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Cardio con combinaciones de golpes sin contacto.', "imagen": 'boxeo_sombra.jpg'},
    {"nombre": 'Patinaje', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Actividad cardiovascular de bajo impacto en ruedas.', "imagen": 'patinaje.jpg'},
    {"nombre": 'Senderismo', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Caminata en terreno natural, intensidad variable.', "imagen": 'senderismo.jpg'},
    {"nombre": 'Remo en aguas abiertas', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Remo en kayak o canoa, trabaja tren superior.', "imagen": 'remo_abierto.jpg'},
    {"nombre": 'Sentadilla sissy', "categoria": 'pesas', "grupo_muscular": 'Cuádriceps',
     "descripcion": 'Aislamiento avanzado de cuádriceps.', "imagen": 'sentadilla_sissy.jpg'},
    {"nombre": 'Peso muerto a una pierna', "categoria": 'pesas', "grupo_muscular": 'Isquiotibiales',
     "descripcion": 'Ejercicio unilateral de equilibrio y fuerza.', "imagen": 'peso_muerto_una_pierna.jpg'},
    {"nombre": 'Puente de glúteo a una pierna', "categoria": 'pesas', "grupo_muscular": 'Glúteos',
     "descripcion": 'Variante unilateral del puente de glúteo.', "imagen": 'puente_gluteo_una_pierna.jpg'},
    {"nombre": 'Press en máquina Smith', "categoria": 'pesas', "grupo_muscular": 'Pecho',
     "descripcion": 'Press de banca guiado en máquina Smith.', "imagen": 'press_smith.jpg'},
    {"nombre": 'Remo T-bar', "categoria": 'pesas', "grupo_muscular": 'Espalda',
     "descripcion": 'Remo con barra en landmine, buen espesor de espalda.', "imagen": 'remo_t_bar.jpg'},
    {"nombre": 'Face pull', "categoria": 'pesas', "grupo_muscular": 'Hombros',
     "descripcion": 'Trabaja deltoide posterior y rotadores.', "imagen": 'face_pull.jpg'},
    {"nombre": 'Curl 21s', "categoria": 'pesas', "grupo_muscular": 'Bíceps',
     "descripcion": 'Técnica de curl en 3 rangos de movimiento.', "imagen": 'curl_21s.jpg'},
    {"nombre": 'Extensión de tríceps sobre la cabeza', "categoria": 'pesas', "grupo_muscular": 'Tríceps',
     "descripcion": 'Aislamiento con mancuerna a dos manos.', "imagen": 'extension_triceps_cabeza.jpg'},
    {"nombre": 'Mountain climbers', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Movimiento dinámico de core y cardio.', "imagen": 'mountain_climbers.jpg'},
    {"nombre": 'GHD sit-up', "categoria": 'crossfit', "grupo_muscular": None,
     "descripcion": 'Abdominal en banco de hiperextensión.', "imagen": 'ghd_situp.jpg'},
    {"nombre": 'Assault bike', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Bicicleta de alta intensidad con resistencia de aire.', "imagen": 'assault_bike.jpg'},
    {"nombre": 'Trote en el lugar', "categoria": 'cardio', "grupo_muscular": None,
     "descripcion": 'Cardio de bajo equipo, ideal para casa.', "imagen": 'trote_lugar.jpg'},
]

app = create_app()

with app.app_context():
    for datos in actividades_ejemplo:
        existente = Actividad.query.filter_by(nombre=datos["nombre"]).first()
        if not existente:
            db.session.add(Actividad(**datos))

    db.session.commit()
    print(f"Listo: {len(actividades_ejemplo)} actividades verificadas/cargadas.")